project:
  type: website
  output-dir: docs

website:
  site-url: https://mastersep.github.io/Site-internet-Master-SEP
  search: true
  reader-mode: true
  
  page-footer: 
      center: "<span style='color: #8b4513;'> Site con√ßu par des √©tudiants du Master SEP üéìüòÅ </span>"
      right:
        - icon: linkedin
          href: https://www.linkedin.com/in/master-sep-a004ba256/
        - icon: facebook
          href: https://www.facebook.com/Master-SEP-Reims-108350474430182
        - icon: github
          href: https://github.com/MasterSEP  
        - icon: instagram
          href: https://www.instagram.com/

  navbar:
    logo: "Images/logo.png"
    background: secondary
    search: true
    left:
      - text: "Pr√©sentation"
        file: index.qmd
      - text: "Formation"
        menu:  # Sous-menu pour Formation
          - text: "Programmes"
            file: Programmes.qmd
          - text: "Organisation"
            file: Organisation.qmd
          - text: "D√©bouch√©s professionnels"
            file: D√©bouch√©s.qmd
          - text: "Modalit√©s"
            file: Modalit√©s.qmd
          - text: "Stage"
            file: Stage.qmd
      - text: "Vie √©tudiante"
        menu:
          - text: "T√©moignages d'anciens"
            file: T√©moignage.qmd
          - text: "Evenements Etudiants"
            file: evenement.qmd
          - text: "Actualit√©s"
            file: Actualites.qmd
          - text: "Outils et ressources"
            file: ressources.qmd
          - text: "Logiciels et environnements √† installer"
            file: logiciel.qmd
      - text: "Contacts"
        file: contacts.qmd
      

    
format:
  html:
    toc: true
    page-layout: full
    theme: 
    - jolla
    - themes.scss
    css: styles.css
    

    

editor: visual

